spring:
  datasource:         # Oracle dataSource 
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@dblab_high?TNS_ADMIN=Users/Oracle/Wallet_DBLab  
    username: ss230109
    password: Spring_105954
    
#    hikari:          # HikariCP settings
#      minimumIdle: 5
#      maximumPoolSize: 20
#      idleTimeout: 30000
#      connectionTimeout: 30000
#      maxLifetime: 2000000
#      poolName: HikariPool          
  mvc:  
    view:             # JSP views
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  devtools:
    livereload:
      enabled: 'true'
      
mybatis:
  type-aliases-package: com.example.jpetstore.domain
#  mapper-locations: com/example/jpetstore/dao/mybatis/mapper/**/*.xml
  
logging:
  level:
    com:
      ssp:
        closet:
          dao:
            mybatis:
              mapper: DEBUG           
  
server:
  port: 8088