spring:
  datasource:         # Oracle dataSource 
    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@dblab_low?TNS_ADMIN=/Users/Oracle/Wallet_DBLab
    url: jdbc:oracle:thin:@(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.ap-seoul-1.oraclecloud.com))(connect_data=(service_name=g4ecfbb775fd1ef_dblab_low.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
    username: ss230109
    password: Spring_105954
    
#    hikari:          # HikariCP settings
#      minimumIdle: 5
#      maximumPoolSize: 20
#      idleTimeout: 30000
#      connectionTimeout: 30000
#      maxLifetime: 2000000
#      poolName: HikariPool          
  mvc:  
    view:             # JSP views
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  jpa:
    database: oracle
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
    generate-ddl: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        # do not changes camel case to snake case, which is the default spring.jpa.hibernate.naming.implicit-strategy 
 
  devtools:
    livereload:
      enabled: true
      

mybatis:
  type-aliases-package: com.ssp.closet.dto
#  mapper-locations: com/example/jpetstore/dao/mybatis/mapper/**/*.xml
    
logging:
  level:
    com:
      ssp:
        closet:
          dao:
            mybatis:
              mapper: DEBUG        
      org:
        hibernate: INFO     
  
server:
  tomcat:
    additional-tld-skip-patterns:
      - oraclepki.jar
      - osdt_core.jar
      - osdt_cert.jar
  port: 8089
